# Generated by Django 5.0.6 on 2024-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(help_text='Tarea a realizar.', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.')),
                ('vencimiento', models.DateTimeField(help_text='Fecha de vencimiento.', null=True)),
            ],
        ),
    ]
