# Generated by Django 5.0.6 on 2024-05-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='tarea',
            new_name='mi_tarea',
        ),
    ]
