# Generated by Django 5.0.6 on 2024-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_rename_mi_tarea_tarea_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento.', null=True),
        ),
    ]
